apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todo
  namespace: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-todo
  template:
    metadata:
      labels:
        app: backend-todo
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend-todo
          image: ghcr.io/kust1q/backend:2.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: do
            - name: SPRING_DATASOURCE_USERNAME
              value: program
            - name: DATABASE_PASSWORDSPRING_DATASOURCE_PASSWORD
              value: test
            - name: DATABASE_PORT
              value: '5432'
            - name: SPRING_DATASOURCE_URL
              value: postgres.practice.svc.cluster.local
            - name: DATABASE_NAME
              value: todo_list
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect